import { codingWidgetHtml } from "./coding-widget.ts";

// Host the same editor in an ordinary authenticated browser pane when the agent
// client does not render MCP Apps. No bearer credential enters the page.
const widget = JSON.stringify(codingWidgetHtml.replace('<script>', '<script>window.ARC_BROWSER_HOST=true;</script><script>')).replace(/</g,"\\u003c");
export const codingBrowserHtml = `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Interview Arc coding editor</title><style>body{margin:0;background:#FBFCFA;color:#102A2A;font:14px/1.5 system-ui}#notice{padding:12px 20px;border-bottom:1px solid #C8D8D3}iframe{display:block;border:0;width:100%;min-height:90vh}</style></head><body><div id="notice" role="status">Edit here, then ask your agent to review the saved draft. Java/Python selection is opened by your agent.</div><iframe title="Editable coding practice" sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"></iframe><script>
const frame=document.querySelector('iframe'),draftId=new URL(location.href).searchParams.get('draftId');
frame.srcdoc=${widget};
const send=m=>frame.contentWindow.postMessage({jsonrpc:'2.0',...m},location.origin);
async function api(args){const save=args.name==='save_coding_draft';if(!save&&args.name!=='get_coding_draft')throw Error('Ask your agent to open the other language or submit your saved code.');if(args.arguments.draftId!==draftId)throw Error('This pane is bound to its opened draft.');const response=await fetch(save?'/api/coding-draft':'/api/coding-draft?draftId='+encodeURIComponent(draftId),save?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(args.arguments)}:{});const data=await response.json();if(!response.ok){if(save)return {isError:true,structuredContent:data,content:[{type:'text',text:data.error||'Save failed.'}]};throw Error(data.error||'The editor could not reach your saved draft.');}return {structuredContent:data};}
window.addEventListener('message',async event=>{if(event.source!==frame.contentWindow||event.origin!==location.origin)return;const m=event.data;if(m?.jsonrpc!=='2.0')return;try{let result={};if(m.method==='ui/initialize')result={protocolVersion:'2026-01-26',hostInfo:{name:'Arc browser',version:'1'},hostCapabilities:{},hostContext:{displayMode:'inline'}};else if(m.method==='ui/notifications/initialized'){const response=await api({name:'get_coding_draft',arguments:{draftId}});send({method:'ui/notifications/tool-result',params:response});return;}else if(m.method==='tools/call')result=await api(m.params);else if(m.method==='ui/message'){document.querySelector('#notice').textContent='Draft saved. Return to your agent and say “Review my saved code.” No code copy or upload is needed.';}else if(m.method==='ui/request-display-mode'){result={mode:'fullscreen'};}else if(m.method==='ui/notifications/size-changed'){frame.style.height=Math.min(2000,Math.max(600,Number(m.params?.height)||600))+'px';return;}if(m.id!==undefined)send({id:m.id,result});}catch(error){if(m.id!==undefined)send({id:m.id,error:{code:-32000,message:error.message}});else document.querySelector('#notice').textContent=error.message;}});
</script></body></html>`;
