import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { drawingInput, readPracticeDrawing, savePracticeDrawing } from "../db/practice-drawing.ts";
export function registerDrawingTools(server:McpServer,db:Pick<D1Database,"prepare"|"batch">,bucket:Pick<R2Bucket,"get"|"put">,owner:string){
  server.registerTool("save_practice_drawing",{
    description:"After the user asks to publish/save a system-design practice, attach its complete Excalidraw snapshot link to the completed imported record returned by apply_practice_backfill. Saves an immutable editable original privately and a link to reopen the snapshot; no PNG/SVG preview is generated in this import flow. Mark assistant-created references as assistant_reference. Requires a real exported #json URL; never invent one or claim unsaved widget edits are included. Keep the same operationId on retries, inspect get_practice_drawing after uncertainty. The transcript save and drawing save have separate receipts; do not claim full publication until both succeed.",
    inputSchema:drawingInput.shape,annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true},
  },async(input)=>{try{const result=await savePracticeDrawing(db,bucket,owner,input);return {content:[{type:"text" as const,text:"Editable drawing saved and verified."}],structuredContent:result};}catch(error){return {isError:true,content:[{type:"text" as const,text:error instanceof Error?error.message:"Drawing save failed."}]};}});
  server.registerTool("get_practice_drawing",{description:"Read the current or exact historical drawing attachment receipt for this owner's imported practice. Returns the share link and authenticated editable-file download, never private backing-store paths.",inputSchema:{activityId:z.string().min(1).max(240),revision:z.number().int().positive().optional()},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async({activityId,revision})=>{const drawing=await readPracticeDrawing(db,owner,activityId,revision);return {content:[{type:"text" as const,text:JSON.stringify({drawing})}],structuredContent:{drawing}};});
}
