import { createDeviceLectureSpeech } from "../lib/lecture-device-speech.ts";
export const lecturePlayerUri="ui://interview-arc/lecture-player-v2.html";
export const lecturePlayerHtml=String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Professor lecture</title><style>
:root{color-scheme:light dark;--paper:#fbfcfa;--ink:#102a2a;--muted:#526962;--line:#c8d8d3;--accent:#0f5f5a}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.6 system-ui,sans-serif}main{padding:22px;max-width:850px;margin:auto}header{border-bottom:1px solid var(--line);padding-bottom:16px}small{font-size:13px;color:var(--muted)}h1{font:32px/1.15 Georgia,serif;margin:6px 0 12px;overflow-wrap:anywhere}p{margin:10px 0}audio{width:100%;margin:20px 0 8px}button,select{font:inherit;min-height:44px;padding:8px 12px;border:1px solid var(--line);border-radius:8px;background:var(--paper);color:var(--ink)}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}button:focus-visible,select:focus-visible,audio:focus-visible{outline:3px solid var(--accent);outline-offset:3px}.actions{display:flex;flex-wrap:wrap;align-items:center;gap:10px}.primary{background:var(--accent);color:white}#error{color:#b63823;white-space:pre-wrap}#chapters{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}#chapters button{text-align:left}#state{min-height:24px}progress{width:100%;accent-color:var(--accent)}@media(prefers-color-scheme:dark){:root{--paper:#122524;--ink:#e8f2ee;--muted:#b1c6bf;--line:#3d5750;--accent:#226e60}#error{color:#ffb5a5}}@media(max-width:480px){main{padding:16px}h1{font-size:27px}}
</style></head><body><main><header><small>INTERVIEW ARC · PROFESSOR</small><h1 id="title">Your lecture</h1><p id="details">Opening saved lecture…</p><small>Free device voice. No speech API, credits or connection to your computer.</small></header>
<div class="actions"><button id="devicePlay" class="primary" disabled>Play free on this device</button><button id="devicePause" disabled>Pause</button></div><p id="deviceState" role="status">Checking this host's local voices…</p>
<p id="state" role="status" aria-live="polite"></p><progress id="progress" value="0" max="1" aria-label="Audio preparation"></progress>
<div class="actions"><button id="generate" hidden disabled>Generate paid API audio</button><button id="stop" hidden>Stop after this section</button><button id="refresh">Refresh / reconnect</button></div>
<audio id="audio" controls preload="metadata"></audio><div class="actions"><label>Speed <select id="speed"><option value="0.75">0.75×</option><option value="1" selected>1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></label><button id="hour" disabled>Fit full lecture to 1 hour</button></div>
<p id="duration"></p><small id="saved">Position has not changed.</small><div id="chapters" aria-label="Lecture chapters"></div><p id="error" role="alert"></p><p><small>Free playback reads every saved section automatically using a voice installed on this device. Keep this player open. Duration is an estimate; background and screen-lock playback depend on ChatGPT. Pause resumes at the last reported word or sentence.</small></p></main><script>
// Wrangler adds function-name annotations when bundling the shared controller.
// They are metadata only; keep their helper local to this serialized script.
const __name=fn=>fn;
const createDeviceLectureSpeech=${createDeviceLectureSpeech.toString()};
const $=id=>document.getElementById(id),audio=$('audio'),pending=new Map();let nextId=1,lecture=null,generating=false,stop=false,saving=null,queued=null,lastSave=0,dirty=false,blocked=false,starts=[],latestPosition=0,canGenerate=false;
let device=null,devicePhase='paused',deviceSave=null;
function deviceVoices(){const local=window.speechSynthesis?.getVoices().some(v=>v.localService&&v.lang.startsWith('en'));$('devicePlay').disabled=!device||!local||['playing','loading','error','finished'].includes(devicePhase);if(!local)$('deviceState').textContent='No local English voice is exposed by this host. No paid request was made.';}
function setupDevice(fragment){device?.dispose();devicePhase='paused';if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){$('deviceState').textContent='This host does not expose device speech. No paid request was made.';return;}
const id=lecture.lectureId;device=createDeviceLectureSpeech({speech:window.speechSynthesis,makeUtterance:text=>new SpeechSynthesisUtterance(text),chunkCount:lecture.chunks.length,chunkIndex:lecture.cursor.chunkIndex,characterOffset:lecture.cursor.characterOffset,
loadChunk:async index=>{if(fragment?.index===index)return fragment.text;const result=await call('get_practice_lecture',{lectureId:id,chunkIndex:index}),data=result.structuredContent;if(data?.fingerprint!==lecture.fingerprint||data?.fragment?.index!==index)throw Error('The original lecture section was not confirmed.');return data.fragment.text;},
savePosition:async(index,offset)=>{deviceSave??={lectureId:id,operationId:'device-'+crypto.randomUUID(),expectedRevision:lecture.cursor.revision,chunkIndex:index,characterOffset:offset,offsetSeconds:0};const result=await call('save_lecture_position',deviceSave),saved=result.structuredContent;if(!saved?.revision)throw Error('Position save was not confirmed. Reload before resuming.');lecture.cursor.revision=saved.revision;deviceSave=null;$('saved').textContent='Saved section '+(index+1)+' · character '+offset+' · revision '+saved.revision;},
onChange:state=>{devicePhase=state.phase;$('deviceState').textContent=state.message||'Playing free · section '+(state.chunkIndex+1)+' of '+lecture.chunks.length+' · character '+state.characterOffset;$('devicePause').disabled=!['playing','loading'].includes(state.phase);deviceVoices();}});device.setRate(Number($('speed').value));$('deviceState').textContent='Ready for free playback on this device.';deviceVoices();}
window.speechSynthesis?.addEventListener('voiceschanged',deviceVoices);
$('devicePlay').onclick=async()=>{audio.pause();if(saving)await saving.catch(()=>{});if(blocked)return;void device?.play().catch(error);};$('devicePause').onclick=()=>device?.pause().catch(error);
window.addEventListener('pagehide',()=>{void device?.pause().catch(()=>{});device?.dispose();});
function notify(method,params){window.parent.postMessage({jsonrpc:'2.0',method,params},'*');}
function request(method,params){const id=nextId++;return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{pending.delete(id);reject(Error('Chat connection timed out. Reconnect and check saved state before retrying.'));},180000);pending.set(id,{resolve,reject,timeout});window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*');});}
async function call(name,args){const result=await request('tools/call',{name,arguments:args});if(result?.isError)throw Error(result.content?.find(c=>c.type==='text')?.text||'Tool failed.');return result;}
function error(e){$('error').textContent=e.message||String(e);}
function time(n){return Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0');}
function duration(){if(!Number.isFinite(audio.duration))return;$('duration').textContent='Recording '+time(audio.duration)+' · listening time '+time(audio.duration/audio.playbackRate)+' at '+audio.playbackRate.toFixed(2)+'×';$('hour').disabled=audio.duration<1800||audio.duration>7200;}
function render(result){const data=result.structuredContent??result; if(!data.lecture)return;dirty=false;queued=null;lecture=data.lecture;blocked=false;$('title').textContent=lecture.title;$('details').textContent=lecture.wordCount+' words · '+lecture.chunks.length+' sections · about '+lecture.estimatedMinutes+' minutes before speech is measured';const count=lecture.chunks.filter(c=>c.audio?.state==='ready').length;$('progress').max=lecture.chunks.length;$('progress').value=count;$('state').textContent=data.ready?'Audio ready. Press Play.':count+' / '+lecture.chunks.length+' sections prepared';canGenerate=!data.ready&&data.speechConfigured;$('generate').disabled=generating||!canGenerate;if(!data.ready)$('state').textContent='Script ready for free playback.';
 starts=[];let offset=0;for(const c of lecture.chunks){starts.push(offset);offset+=c.audio?.duration_seconds??0;}
 const url=result._meta?.audioUrl;if(url){const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.origin!=='https://limitless-mcp.vinosama.workers.dev')throw Error('Unrecognized audio origin.');audio.src=url;latestPosition=(starts[lecture.cursor.chunkIndex]??0)+lecture.cursor.offsetSeconds;audio.onloadedmetadata=()=>{audio.currentTime=Math.min(latestPosition,audio.duration);duration();};}else{audio.removeAttribute('src');audio.load();}
 $('chapters').replaceChildren();let last='';for(const c of lecture.chunks){if(c.sectionId===last)continue;last=c.sectionId;const b=document.createElement('button');b.textContent=c.sectionTitle;b.onclick=()=>{if(data.ready){audio.currentTime=starts[c.index];dirty=true;}else void device?.seek(c.index).catch(error);};$('chapters').appendChild(b);} $('saved').textContent='Saved position revision '+lecture.cursor.revision;deviceSave=null;setupDevice(result._meta?.scriptFragment);audio.hidden=!data.ready;$('hour').hidden=!data.ready;$('progress').hidden=!data.ready;
}
async function refresh(){if(!lecture)return;await device?.pause();if(saving)await saving.catch(()=>{});if(dirty&&!blocked)await save();const result=await call('open_practice_lecture_player',{lectureId:lecture.lectureId});render(result);$('error').textContent='';}
async function save(){if(!lecture||blocked||!dirty)return;if(saving)return saving;saving=(async()=>{do{const position=audio.currentTime;let index=starts.findLastIndex(n=>n<=position);index=Math.max(0,index);const seconds=Math.min(Math.max(0,position-starts[index]),lecture.chunks[index].audio?.duration_seconds??0);queued??={lectureId:lecture.lectureId,operationId:'player-'+crypto.randomUUID(),expectedRevision:lecture.cursor.revision,chunkIndex:index,offsetSeconds:seconds,characterOffset:0};const result=await call('save_lecture_position',queued),saved=result.structuredContent;if(!saved?.revision)throw Error('Position save was not confirmed.');lecture.cursor.revision=saved.revision;queued=null;dirty=Math.abs(audio.currentTime-position)>.5;$('saved').textContent='Saved '+time(position)+' · revision '+saved.revision;}while(dirty&&!blocked);})().catch(e=>{blocked=true;audio.pause();error(e);$('saved').textContent='Save needs attention. Reconnect before resuming.';throw e;}).finally(()=>{saving=null;});return saving;}
audio.addEventListener('play',()=>{if(['playing','loading'].includes(devicePhase)){audio.pause();void device.pause().catch(error);return;}if(blocked){audio.pause();return;}dirty=true;});audio.addEventListener('timeupdate',()=>{if(audio.paused||blocked)return;dirty=true;if(Date.now()-lastSave>10000){lastSave=Date.now();save().catch(()=>{});}});audio.addEventListener('pause',()=>{if(dirty&&!blocked)save().catch(()=>{});});audio.addEventListener('ended',()=>{dirty=true;save().catch(()=>{});});audio.addEventListener('error',()=>{if(audio.getAttribute('src'))error(Error('Playback could not load. Refresh the player to renew its audio access.'));});
$('speed').onchange=()=>{audio.playbackRate=Number($('speed').value);device?.setRate(audio.playbackRate);duration();};$('hour').onclick=()=>{if(audio.duration>=1800&&audio.duration<=7200){audio.playbackRate=audio.duration/3600;duration();}};
$('refresh').onclick=()=>refresh().catch(error);$('stop').onclick=()=>{stop=true;$('state').textContent='Finishing the current section, then stopping.';};
$('generate').onclick=async()=>{if(!lecture)return;generating=true;stop=false;$('generate').disabled=true;$('stop').hidden=false;$('error').textContent='';try{for(const c of lecture.chunks){if(stop)break;if(c.audio?.state==='ready')continue;$('state').textContent='Generating section '+(c.index+1)+' of '+lecture.chunks.length;await call('generate_lecture_audio_section',{lectureId:lecture.lectureId,chunkIndex:c.index});$('progress').value=Number($('progress').value)+1;}await refresh();}catch(e){error(e);}finally{generating=false;$('stop').hidden=true;$('generate').disabled=!canGenerate;}};
window.addEventListener('message',event=>{if(event.source!==window.parent)return;const m=event.data;if(!m||m.jsonrpc!=='2.0')return;const p=pending.get(m.id);if(p){pending.delete(m.id);clearTimeout(p.timeout);if(m.error)p.reject(Error(m.error.message));else p.resolve(m.result);return;}if(m.method==='ui/notifications/tool-result'&&!generating&&!saving&&!['playing','loading'].includes(devicePhase))try{render(m.params);}catch(e){error(e);}});
new ResizeObserver(()=>notify('ui/notifications/size-changed',{height:document.querySelector('main').getBoundingClientRect().height})).observe(document.querySelector('main'));
request('ui/initialize',{protocolVersion:'2026-01-26',appInfo:{name:'Interview Arc Professor',version:'1.0.0'},appCapabilities:{}}).then(()=>{notify('ui/notifications/initialized',{});if(window.openai?.toolOutput)render({structuredContent:window.openai.toolOutput,_meta:window.openai.toolResponseMetadata});}).catch(error);
</script></body></html>`;
